drop table if exists shared_clinical_and_rfs;

create table shared_clinical_and_rfs (
primary_id_decimal int,
patient_id varchar(30),
race varchar(40),
caucasian_race varchar(30),
breast_laterality varchar(30),
age_at_mr1 decimal(5,1),
er_positive  int,
pr_positive  int,
her2_positive int,
er_pr_her2_tested varchar(10),
hr_her2_category int,
hr_her2_status varchar(30),
mri_1 varchar(10),
mri_2 varchar(10),
mri_3 varchar(10),
mri_4 varchar(10),
ld_1  decimal(6,2),
ld_2  decimal(6,2),
ld_3  decimal(6,2),
ld_4  decimal(6,2), 
ser_volume_1 decimal(6,2),
ser_volume_2 decimal(6,2),
ser_volume_3 decimal(6,2), 
ser_volume_4 decimal(6,2),
chemo varchar(10),
ac_only_or_taxol int,
clinical_size_pre decimal(6,2),
clinical_size_post decimal(6,2),
clinical_response int,
cancer_type varchar(40),
surgery_type varchar(20),
path_size decimal(6,2),
ln int,
censor int,
dfs_time int,
recur_type varchar(20),
comments varchar(1024),
filler1 varchar(10),
filler2 varchar(10),
volume_1 decimal(9,3),
volume_2 decimal(9,3),
volume_3 decimal(9,3),
volume_4 decimal(9,3)
);

\copy shared_clinical_and_rfs from 'SharedClinicalAndRFS_only_data.csv' delimiter ',' csv header
 
